### ISSUE TITLE
Depth Zero Signature Not Working

### ISSUE THREAD

**Issue by MapleOx** [datasig-ac-uk/RoughPy#177]
**Describe the bug**
When I run the first example in the RoughPy tutorial (https://roughpy.org/user/absolute_beginners.html) and ask it to compute the depth-0 signature, it gives me the depth-2 signature instead.

**To Reproduce**
Run the following code:

```
import roughpy as rp
import numpy as np

word = "stream"
CTX = rp.get_context(width=26, depth=0, coeffs=rp.Rational)

def word_to_stream(word):
    increment_array = np.zeros((len(word), 26), dtype=np.int8)
    for i, letter in enumerate(word):
        letter_idx = ord(letter)
        assert 97 <= letter_idx <= 122, f"expected lower case letter, got {letter}"
        increment_array[i, letter_idx - 97] = 1

    return rp.LieIncrementStream.from_increments(increment_array, resolution=2, ctx=CTX)

stream = word_to_stream(word)
signature = stream.signature()
print(signature)
```

**Expected behavior**
I expected to see the output `{ 1() }`, which is the depth-0 signature.

**Actual behavior**
Instead, the output is the depth-2 signature
`{ 1() 1(1) 1(5) 1(13) 1(18) 1(19) 1(20) 1/2(1,1) 1(1,13) 1(5,1) 1/2(5,5) 1(5,13) 1/2(13,13) 1(18,1) 1(18,5) 1(18,13) 1/2(18,18) 1(19,1) 1(19,5) 1(19,13) 1(19,18) 1/2(19,19) 1(19,20) 1(20,1) 1(20,5) 1(20,13) 1(20,18) 1/2(20,20) }`.

**Additional context**
I have observed this in other experiments as well. Is the code somehow computing the depth-2 signature by default when it is given depth = 0?

**Comment by inakleinbottle** [comment]
This is clearly a bug, I will look into it when I get a chance.

I suspect that a depth of 0 is being replaced internally because it is an unusual value, but I don't know for sure.

**Comment by MapleOx** [comment]
Thanks for the quick response!

**Comment by inakleinbottle** [comment]
I can't identify the cause of this from a quick look at the source code, but in any case this should be regarded as undefined behaviour. (From a practical point of view, depth 0 does not give any interesting paths.) I've added some quick checks in the `get_context` function to raise an exception if either width or depth is requested as 0.
