### ISSUE TITLE
TypeError: Unregistered type : rpy::algebra::Basis<rpy::algebra::TensorBasisInterface>

### ISSUE THREAD

**Issue by SimonBreneis** [datasig-ac-uk/RoughPy#38]
If I execute the example list_basis_keys.py on this Github project, I get the error

Traceback (most recent call last):
  File "C:\...\main.py", line 14, in <module>
    basis = context.tensor_basis
TypeError: Unregistered type : rpy::algebra::Basis<rpy::algebra::TensorBasisInterface>

**Comment by terrylyons** [comment]
I am getting output I don't understand from this example code as well. In the jupyter notebook for the electricity I write:

`
cycles = [rp.RealInterval((i/50), (i/50)+.02) for i in range(2864*50, 2874*50, 1)]
lsigs = np.vstack([np.array(stream.log_signature(cycle, depth = 3)) for cycle in cycles])
lsigs_context = rp.get_context(2, 3, rp.DPReal)
Columns = [str(x) for x in lsigs_context.lie_basis]
print(Columns)
` 
and for output I get 

> ['1', '1', '[1,2]', '[1,1]', '[2,1]'] 

Which is really not correct.

**Comment by inakleinbottle** [comment]
I've opened a new issue for @terrylyons issue since it doesn't seem to be related. I'm looking in to this.

**Comment by inakleinbottle** [comment]
@SimonBreneis I need some additional information to debug this properly. Can you please run the following in the terminal and past the output here:
```
pip list
```
The output should look something look something like this:
```
Package                       Version
----------------------------- --------
alabaster                     0.7.13
Babel                         2.12.1
build                         0.10.0
certifi                       2023.5.7
charset-normalizer            3.1.0
docutils                      0.20.1
exceptiongroup                1.1.1
idna                          3.4
imagesize                     1.4.1
iniconfig                     2.0.0
Jinja2                        3.1.2
MarkupSafe                    2.1.3
numpy                         1.25.0
packaging                     23.1
pip                           23.1.2
```

**Comment by SimonBreneis** [comment]
pip list yields the following output:

Package            Version
------------------ --------
appdirs            1.4.4
brotlipy           0.7.0
certifi            2023.5.7
cffi               1.15.1
charset-normalizer 2.0.4
contourpy          1.0.5
cryptography       39.0.1
cycler             0.11.0
esig               0.9.8.3
fbm                0.3.0
fonttools          4.25.0
idna               3.4
kiwisolver         1.4.4
matplotlib         3.7.1
mkl-fft            1.3.6
mkl-random         1.2.2
mkl-service        2.4.0
mpmath             1.2.1
munkres            1.1.4
numpy              1.25.0
packaging          23.0
Pillow             9.4.0
pip                23.1.2
ply                3.11
pooch              1.4.0
pycparser          2.21
pyOpenSSL          23.0.0
pyparsing          3.0.9
PyQt5              5.15.7
PyQt5-sip          12.11.0
PySocks            1.7.1
python-dateutil    2.8.2
requests           2.29.0
roughpy            0.0.2a0
scipy              1.10.1
setuptools         67.8.0
sip                6.6.2
six                1.16.0
sympy              1.11.1
toml               0.10.2
tornado            6.2
urllib3            1.26.16
wheel              0.38.4
win-inet-pton      1.1.0

**Comment by inakleinbottle** [comment]
Ok, the problem here is that your version of RoughPy is too old to support the example code. You will need to update RoughPy to at least the current version (Version 0.0.7) in order to run these examples.

Since RoughPy is under active development, new versions are released fairly quickly, so it is worth checking every now and again whether the version you have is the most up-to-date.

**Comment by SimonBreneis** [comment]
Thank you, this seems to have resolved the problem!

However, now when I try the following command:
stream = rp.LieIncrementStream.from_increments([[0., 1., 2.], [3., 4., 5.]], depth=2)
which also appears in the ReadMe file, I get the error message

Traceback (most recent call last):
  File "C:\...\main.py", line 120, in <module>
    stream = rp.LieIncrementStream.from_increments([[0., 1., 2.], [3., 4., 5.]], depth=2)
RuntimeError: could not deduce the scalar type of the source at lineno 168 in D:\a\RoughPy\RoughPy\scalars\include\roughpy/scalars/scalar_type_helper.h in function rpy::scalars::impl_helpers::ScalarTypeHelper<double,double>::copy_convert

**Comment by terrylyons** [comment]
I think this will be fixed by adding  dtype=rp.DPReal,

I use the following commands

stream = rp.ExternalDataStream.from_uri(
    data_path,
    channel_types=[rp.ValueChannel, rp.IncrementChannel],
    width=2, depth=6, dtype=rp.DPReal, resolution=resolution)

to build a stream from a flac file.
________________________________

**Comment by inakleinbottle** [comment]
I've created a new issue for your second error. This is resolved by explicitly providing a dtype as @terrylyons suggests. Closing this issue now.
