### ISSUE TITLE
MacOS-M2 - issue 

### ISSUE THREAD

**Issue by urbanist-ai** [datasig-ac-uk/RoughPy#43]
I have tried to install the RoughPy on macOS-M2, it did not work. It gave me the following error:   error: subprocess-exited-with-error
  
  × Building wheel for roughpy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      2023-10-06 14:43:44,066 - scikit_build_core - INFO - CMake version: 3.27.6
      version {'regex': '^(?P<prefix>v)?(?P<version>[^\\+]+)(?P<suffix>.*)?$'}
      *** scikit-build-core 0.5.1 using CMake 3.27.6 (wheel)
      2023-10-06 14:43:44,068 - scikit_build_core - INFO - Build directory: /private/var/folders/g6/dg1gwl0j4_33mp2w55441lm80000gn/T/tmpgzt0tutf/build
      *** Configuring CMake...
      2023-10-06 14:43:44,170 - scikit_build_core - INFO - Ninja version: 1.11.1
      2023-10-06 14:43:44,170 - scikit_build_core - WARNING - libdir/ldlibrary: /Users/mibrahim/anaconda3/lib/libpython3.10.a is not a real file!
      2023-10-06 14:43:44,170 - scikit_build_core - WARNING - Can't find a Python library, got libdir=/Users/mibrahim/anaconda3/lib, ldlibrary=libpython3.10.a, multiarch=darwin, masd=None
      loading initial cache file /var/folders/g6/dg1gwl0j4_33mp2w55441lm80000gn/T/tmpgzt0tutf/build/CMakeInit.txt
      -- Toolchain file:
      -- Repository version v0.0.7
      
      -- The C compiler identification is AppleClang 14.0.3.14030022
      -- The CXX compiler identification is AppleClang 14.0.3.14030022
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- SKBuild environment: /Users/mibrahim/anaconda3/bin
      -- Found Python: /Users/mibrahim/anaconda3/bin/python (found suitable version "3.10.9", minimum required is "3.8") found components: Interpreter Development.Module NumPy
      '/Users/mibrahim/anaconda3/bin/python' '-m' 'pybind11' '--cmakedir'
      -- Adding Pybind11 cmake dir /private/var/folders/g6/dg1gwl0j4_33mp2w55441lm80000gn/T/pip-build-env-oy2ytcbs/overlay/lib/python3.10/site-packages/pybind11/share/cmake/pybind11
      CMake Error at /private/var/folders/g6/dg1gwl0j4_33mp2w55441lm80000gn/T/pip-build-env-oy2ytcbs/normal/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find Boost (missing: Boost_INCLUDE_DIR url) (Required is at least
        version "1.81")
      Call Stack (most recent call first):
        /private/var/folders/g6/dg1gwl0j4_33mp2w55441lm80000gn/T/pip-build-env-oy2ytcbs/normal/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
        /private/var/folders/g6/dg1gwl0j4_33mp2w55441lm80000gn/T/pip-build-env-oy2ytcbs/normal/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/FindBoost.cmake:2392 (find_package_handle_standard_args)
        CMakeLists.txt:160 (find_package)
      
      
      -- Configuring incomplete, errors occurred!
      
      *** CMake configuration failed
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for roughpy
Failed to build roughpy
ERROR: Could not build wheels for roughpy, which is required to install pyproject.toml-based projects

**Comment by inakleinbottle** [comment]
I've just made some changes to the build system so manually installing and adding the toolchain file is no longer necessary. With the next release, you will be able to just pip install even when there is no binary wheel available and it should just build.
