### ISSUE TITLE
Issue with example of LieIncrementStream from README

### ISSUE THREAD

**Issue by lingyiyang** [datasig-ac-uk/RoughPy#46]
The following line from README is not working.

```
stream = rp.LieIncrementStream.from_increments([[0., 1., 2.], [3., 4., 5.]], depth=2)
```
Please see screenshot below of the error
<img width="1039" alt="Screenshot 2023-11-01 at 12 13 25" src="https://github.com/datasig-ac-uk/RoughPy/assets/32545733/bc03736d-b99e-45f9-88f9-92d2a67d7771">

The example `signature-kernel-by-signature-dot.py` works fine which includes adding a context with the following lines:

```
ctx = rp.get_context(width=2, depth=6, coeffs=rp.DPReal)

stream1 = rp.LieIncrementStream.from_increments(p1_data, indices=times, ctx=ctx)
```

I have inputting the separate arguments of ctx in directly into LieIncrementStream (in all combinations possible) without any success. Is context an essential component? If so, please update README.

**Comment by inakleinbottle** [comment]
I've pushed a direct fix to this to the Readme on main today. Passing a Numpy array instead of a list-of-lists works as intended. More fixes for the readme are coming soon too.
