### ISSUE TITLE
Cannot construct a stream from Lie objects

### ISSUE THREAD

**Issue by lingyiyang** [datasig-ac-uk/RoughPy#83]
I would like to construct a stream given that I have a list of Lie objects (which are previously computed log signatures). Since it appears that `LieIncrementStream.from_increments` does not actually take Lie objects, I tried using `PiecewiseAbelianStream.construct` instead by creating a list of (RealInterval, Lie) objects. However, this does not seem to work as there is some issue with inferring width/depth/ctype

<img width="1010" alt="Screenshot 2024-02-23 at 10 33 00" src="https://github.com/datasig-ac-uk/RoughPy/assets/32545733/fda9b012-8e73-401e-ab52-427c06f0673c">

**Comment by lingyiyang** [comment]
The full code to reproduce the error above is:

``` python
CTX = rp.get_context(width=2, depth=2, coeffs=rp.Rational)
word_stream = rp.LieIncrementStream.from_increments(np.array([[0., 1.], [1., 0.], [1., 0.], [0., 1.]]), resolution=2, ctx=CTX)
sig1 = word_stream.log_signature(depth=2)
word_stream = rp.LieIncrementStream.from_increments(np.array([[0., 1.], [0., 1.], [1., 0.], [0., 1.]]), resolution=2, ctx=CTX)
sig2 = word_stream.log_signature(depth=2)
rp.PiecewiseAbelianStream.construct([(rp.RealInterval(0.,1.), sig1), (rp.RealInterval(1.,2.), sig2)])
```

I have also tried constructing the `PiecewiseAbelianStream` with only a single Lie
``` python
rp.PiecewiseAbelianStream.construct([(rp.RealInterval(0.,1.), sig1)])
```
also without success.

**Comment by inakleinbottle** [comment]
OK, so it looks like the thing that is actually missing is the deduction of context from the input Lie elements.

**Comment by terrylyons** [comment]
Hi Sam

Sounds good. Can I ask that the constructor deduces and optionally casts. I can easily imagine wanting the stream to have higher degree than the elements used to construct it.

Terry

On 23 Feb 2024, at 13:57, inakleinbottle ***@***.***> wrote:

﻿

OK, so it looks like the thing that is actually missing is the deduction of context from the input Lie elements.

**Comment by inakleinbottle** [comment]
Depth is never deduced from the data - it can't easily be deduced higher than level 1.

I've rewritten the data parser and it should now be much more flexible and, hopefully, allow the construction of streams using a list of Lies. I'm just writing tests now.
