### ISSUE TITLE
Using DyadicInterval.to_dyadic_intervals() with RealInterval throws an error

### ISSUE THREAD

**Issue by vchhabra-turing** [datasig-ac-uk/RoughPy#95]
**Describe the bug**
Passing a RealInterval into DyadicInterval.to_dyadic_intervals() throws a TypeError.

**To Reproduce**

The code snippet below reproduces the error.
```
import roughpy as rp

interval = rp.RealInterval(0,1)
dyadic_intervals = rp.DyadicInterval.to_dyadic_intervals(interval)
print(dyadic_intervals)
```

**Expected behavior**
I expected a list of DyadicIntervals to be returned, instead I get:

```
TypeError: to_dyadic_intervals(): incompatible function arguments. The following argument types are supported:
    1. (interval: roughpy._roughpy.Interval, resolution: int, interval_type: roughpy._roughpy.IntervalType) -> List[roughpy._roughpy.DyadicInterval]
    2. (inf: float, sup: float, resolution: int, interval_type: roughpy._roughpy.IntervalType) -> List[roughpy._roughpy.DyadicInterval]

Invoked with: RealInterval(inf=0.000000, sup=1.000000, type=clopen)
```

**Screenshots**
<img width="1512" alt="Screenshot 2024-09-05 at 20 57 37" src="https://github.com/user-attachments/assets/3a592ca3-78b0-4756-8469-cdcde1f0997b">

**Desktop (please complete the following information):**
 - OS: Linux (ubuntu 24.04)
 - Python 3.12.3 [GCC 13.2.0]

**Comment by vchhabra-turing** [comment]
Update: I realised the issue is that 1) I wasn't passing in the resolution argument, and 2) the IntervalType needs to be passed in explicitly. For example, with `interval = rp.RealInterval(0,100)` both `rp.DyadicInterval.to_dyadic_intervals(interval)` and `rp.DyadicInterval.to_dyadic_intervals(interval, 2)` will return the above type error, however

`rp.DyadicInterval.to_dyadic_intervals(interval, 2, rp.IntervalType.Clopen)`

will run as intended. Also, the overload does also work similarly:

`rp.DyadicInterval.to_dyadic_intervals(0,100,2, rp.IntervalType.Clopen)`

The last two both (correctly) return the same result:
`[Interval(inf=0.000000, sup=64.000000, type=clopen), Interval(inf=64.000000, sup=96.000000, type=clopen), Interval(inf=96.000000, sup=100.000000, type=clopen)]`

**Comment by inakleinbottle** [comment]
OK so it seems the problem here is that the "optional" interval type argument does not have default argument (making it mandatory). The default value for the argument should be set to `IntervalType::Clopen`, which is the only interval type that is available right now.
